version: '2'

services:
  backend:
    build: ./
    ports:
      - '5000:5000'
    working_dir: /Users/adamsouthey/newDevelopment/mernRedux
    volumes:
      - ./:/Users/adamsouthey/newDevelopment/mernRedux
    depends_on:
      - mongodb
  frontend:
    build: ./client
    ports:
      - '3000:3000'
    working_dir: /Users/adamsouthey/newDevelopment/mernRedux/client
    volumes:
      - ./client:/Users/adamsouthey/newDevelopment/mernRedux/client
    depends_on:
      - backend
  mongodb:
    image: 'mongo'
    ports:
      - '27017:27017'
